sonar.projectKey=Lirni_php-project-48
sonar.organization=lirni

sonar.sources=src,bin
sonar.tests=tests
sonar.php.tests.reportPath=build/logs/phpunit.xml
sonar.php.coverage.reportPath=build/logs/clover.xml

sonar.sourceEncoding=UTF-8